const $=s=>document.querySelector(s);
const routes={};
const colors={'他社線（北陸）':'#bf387b','近畿':'#1673b6','北陸':'#008577','岡山・福山':'#bf7900','広島・山口':'#aa4360','山陰':'#6658a1','新幹線・博多南':'#204cad'};
catalogue.forEach(([area,name,names],i)=>{const ns=names.split('|'),loop=name==='大阪環状線';const stations=ns.map((name,j)=>{const a=-Math.PI/2+j/ns.length*Math.PI*2;return loop?[name,450+260*Math.cos(a),320+220*Math.sin(a)]:[name,100+j/(ns.length-1)*700,450-j/(ns.length-1)*260+(j%2)*20]});routes['r'+i]={name,area,code:loop?'O':'W',color:colors[area],loop,stations,trains:Array.from({length:4},(_,j)=>({id:'D'+String(i+1).padStart(2,'0')+(j+1),p:(j+.4)/4*(ns.length-1),dir:j%2?1:-1,type:name.includes('新幹線')?(name.startsWith('山陽')?['のぞみ','さくら','ひかり','こだま'][j]:['かがやき','はくたか','つるぎ','かがやき'][j])+'（模擬）':j===3?'回送（模擬）':j===2?'貨物（模擬）':'旅客（模擬）'}))}});
const areas=[...new Set(catalogue.map(x=>x[0]))];$('#area').innerHTML='<option value="all">全エリア</option>'+areas.map(a=>'<option>'+a+'</option>').join('');
function fillLines(){const a=$('#area').value;$('#line').innerHTML=areas.filter(x=>a==='all'||x===a).map(area=>'<optgroup label="'+area+'">'+Object.entries(routes).filter(([,r])=>r.area===area).map(([k,r])=>'<option value="'+k+'">'+r.name+'</option>').join('')+'</optgroup>').join('')}
fillLines();
let key='r0',selected='D011',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,last=performance.now();
const route=()=>routes[key];
function loc(t){const r=route(),n=r.stations.length,p=((t.p%n)+n)%n,a=Math.floor(p),f=p-a,b=(a+1)%n;return {a,b,f,x:r.stations[a][1]*(1-f)+r.stations[b][1]*f,y:r.stations[a][2]*(1-f)+r.stations[b][2]*f,from:t.dir===1?a:b,to:t.dir===1?b:a,progress:t.dir===1?f:1-f};}
function direction(t){return route().loop?(t.dir===1?'外回り':'内回り'):(route().stations[t.dir===1?route().stations.length-1:0][0]+' 方面')}
function position(t){const l=loc(t),s=route().stations;return `${s[l.from][0]} → ${s[l.to][0]}`}
function renderBase(){const r=route();document.documentElement.style.setProperty('--accent',r.color);$('#line-name').textContent=r.name;$('#line-code').textContent=r.code;$('#count').textContent=r.trains.length+'本';const path=r.stations.map((s,i)=>`${i?'L':'M'}${s[1]},${s[2]}`).join(' ')+(r.loop?' Z':'');$('#map').innerHTML=`<path d="${path}" fill="none" stroke="${r.color}" stroke-width="18" stroke-linejoin="round" opacity=".09"/><path d="${path}" fill="none" stroke="${r.color}" stroke-width="6" stroke-linejoin="round"/>${r.stations.map((s,i)=>`<circle cx="${s[1]}" cy="${s[2]}" r="9" fill="white" stroke="${r.color}" stroke-width="4"/><text x="${s[1]}" y="${s[2]-24}" text-anchor="middle" font-size="19" fill="#24454f" font-weight="500">${s[0]}</text><text x="${s[1]}" y="${s[2]+30}" text-anchor="middle" font-size="12" fill="#6d858d">${r.code}${String(i+1).padStart(2,'0')}</text>`).join('')}${r.loop?'<text x="445" y="295" text-anchor="middle" font-size="13" letter-spacing="4" fill="#7e999d">OSAKA LOOP</text><text x="445" y="338" text-anchor="middle" font-size="27" fill="#365f65">大阪環状線</text><text x="445" y="371" text-anchor="middle" font-size="14" fill="#7b949a">主要駅のみ表示</text>':''}<g id="markers"></g>`;$('#trains').innerHTML=r.trains.map(t=>`<button class="train-row" data-id="${t.id}" aria-pressed="false"><span class="row-top"><span class="train-no">${t.id}</span><span class="type">${t.type}</span></span><span class="direction">${direction(t)}</span><span class="position"></span></button>`).join('');document.querySelectorAll('.train-row').forEach(b=>b.onclick=()=>{selected=b.dataset.id;update()});$('#markers').innerHTML=r.trains.map(t=>`<g id="marker-${t.id}" tabindex="0" role="button" aria-label="${t.id}の詳細" style="cursor:pointer"><circle class="halo" r="28" fill="${r.color}" opacity=".15"/><rect x="-26" y="-13" width="52" height="26" rx="7" fill="${r.color}" stroke="white" stroke-width="3"/><text x="0" y="5" text-anchor="middle" font-size="12" font-weight="700" fill="white">${t.id.slice(1)}</text></g>`).join('');r.trains.forEach(t=>{const m=$('#marker-'+t.id);m.onclick=()=>{selected=t.id;update()};m.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selected=t.id;update()}}});update();}
function update(){const r=route();r.trains.forEach(t=>{const l=loc(t),el=$('#marker-'+t.id);el.setAttribute('transform',`translate(${l.x},${l.y})`);el.querySelector('.halo').style.display=t.id===selected?'':'none';const row=$(`[data-id="${t.id}"]`);row.classList.toggle('active',t.id===selected);row.setAttribute('aria-pressed',String(t.id===selected));row.querySelector('.position').textContent=position(t);row.querySelector('.direction').textContent=direction(t)});const t=r.trains.find(t=>t.id===selected),l=loc(t);$('#detail').innerHTML=`<h2 class="big-number">${t.id}</h2><p class="detail-direction">${direction(t)}</p><div class="detail-status">${paused?'一時停止中':'走行シミュレーション中'}</div><dl><div><dt>路線</dt><dd>${r.name}</dd></div><div><dt>現在の区間</dt><dd>${position(t)}</dd></div></dl><div class="next-station"><p>次の表示駅</p><strong>${r.stations[l.to][0]}</strong><div class="progress"><div style="width:${l.progress*100}%"></div></div></div><p class="detail-note">位置はデモ用に自動で動きます。<br>時刻表や実際の運行データには連動していません。</p>`;$('#pause').textContent=paused?'▶ 動きを再開':'Ⅱ 動きを止める';$('#pause').setAttribute('aria-pressed',String(paused))}
$('#area').onchange=()=>{fillLines();key=$('#line').value;selected=route().trains[0].id;renderBase()};$('#line').onchange=e=>{key=e.target.value;selected=route().trains[0].id;renderBase()};$('#pause').onclick=()=>{paused=!paused;update()};renderBase();setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,1);last=now;if(paused||document.hidden)return;route().trains.forEach(t=>{t.p+=t.dir*dt*.055;if(!route().loop){const max=route().stations.length-1;if(t.p>=max){t.p=max-.001;t.dir=-1}if(t.p<=0){t.p=.001;t.dir=1}}});update()},250);

document.querySelectorAll('[data-route-name]').forEach(button=>button.onclick=()=>{const entry=Object.entries(routes).find(([,r])=>r.name===button.dataset.routeName);if(!entry)return;$('#area').value=entry[1].area;fillLines();key=entry[0];$('#line').value=key;selected=route().trains[0].id;renderBase()});
