const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lines=[],active='hapi',selected=null,states=new Map(),loading=false,lastCycle=0,timer;
const unsupported=[{id:'sanyo-shinkansen',name:'山陽新幹線',area:'新幹線',unsupported:true},{id:'hokuriku-shinkansen',name:'北陸新幹線',area:'新幹線',unsupported:true}];
const colors={'他社線（北陸）':'#bf387b','北陸':'#008577','近畿':'#1673b6','岡山・福山':'#b47500','広島・山口':'#aa4360','山陰':'#6658a1','新幹線':'#204cad'};
const when=t=>t&&Number.isFinite(Date.parse(t))?new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'不明';
async function api(path,signal){const r=await fetch(RAIL_API+path,{signal,cache:'no-store'});if(!r.ok)throw Error('データ取得に失敗しました');return r.json()}
function fillLines(){const area=$('#area').value;$('#line').innerHTML=[...new Set(lines.map(l=>l.area))].filter(a=>area==='all'||area===a).map(a=>`<optgroup label="${esc(a)}">${lines.filter(l=>l.area===a).map(l=>`<option value="${esc(l.id)}">${esc(l.name)}${l.range?' / '+esc(l.range):''}${l.unsupported?'（未対応）':''}</option>`).join('')}</optgroup>`).join('')}
function choose(id){active=id;selected=null;$('#line').value=id;render()}
function status(){const data=states.get(active),meta=lines.find(l=>l.id===active);let text='取得中';if(meta?.unsupported)text='データ未接続';else if(data?.error)text='取得失敗';else if(data?.updatedAt)text=Date.now()-Date.parse(data.updatedAt)>180000?'更新が遅れています':'実データ';$('#line-status').textContent=text;$('#source-time').textContent=meta?.unsupported?'新幹線の実データは未接続':data?.updatedAt?'提供元更新 '+when(data.updatedAt)+'（日本時間）':data?.error?'取得失敗 · 30秒ごとに再試行':'提供元の更新時刻を確認中';$('#line-status').classList.toggle('warning',text!=='実データ');}
function render(){const meta=lines.find(l=>l.id===active);if(!meta)return;const data=states.get(active);document.documentElement.style.setProperty('--accent',colors[meta.area]||'#1673b6');$('#line-name').textContent=meta.name;$('#line-code').textContent=active==='hapi'?'H':'W';$('#range').textContent=meta.range||'';$('#provider').textContent='';status();
  if(meta.unsupported){$('#trains').innerHTML='<p class="state-message">実データの取得先を確認中です。</p>';$('#rail-map').innerHTML='<div class="empty-state"><h2>この路線はまだ未対応です</h2><p>列車位置を推測で表示することはありません。</p><a href="https://www.jr-odekake.net/railroad/" target="_blank" rel="noopener">JRおでかけネットで確認 ↗</a></div>';$('#detail').innerHTML='<p class="state-message">接続済みの在来線を選んでください。</p>';$('#count').textContent='—';return;}
  if(!data||data.error){$('#count').textContent='—';$('#trains').innerHTML='<p class="state-message">'+(data?.error?'データを取得できませんでした。次回の更新で再試行します。':'最新の列車データを取得しています。')+'</p>';$('#rail-map').innerHTML='<div class="empty-state"><h2>'+(data?.error?'現在位置を確認できません':'データを取得中')+'</h2><p>公式の走行位置もご確認いただけます。</p><a href="'+esc(meta.source||'https://www.train-guide.westjr.co.jp/')+'" target="_blank" rel="noopener">公式ページを開く ↗</a></div>';$('#detail').innerHTML='';return;}
  const trains=data.trains||[];if(!trains.some(t=>t.id===selected))selected=trains[0]?.id;$('#count').textContent=trains.length+'本';
  $('#trains').innerHTML=trains.length?trains.map(t=>`<button class="train-row ${selected===t.id?'active':''}" data-train="${esc(t.id)}" aria-pressed="${selected===t.id}"><span class="row-top"><span class="train-no">${esc(t.name||t.number)}</span><span class="type">${esc(t.type)}</span></span><span class="direction">${esc(t.destination)}${t.destination==='案内なし'?'':' 方面'}</span><span class="position">${esc(t.position)}</span>${t.delayMinutes>0?`<span class="delay">${esc(t.delayMinutes)}分遅れ</span>`:''}</button>`).join(''):'<p class="state-message">表示対象の列車はありません。運行の有無は公式情報もご確認ください。</p>';
  $('#rail-map').innerHTML=data.stations.map(s=>{const ts=trains.filter(t=>t.stationId===s.id);return `<div class="rail-stop"><div class="rail-station"><span class="rail-dot"></span><strong>${esc(s.name)}</strong></div><div class="rail-trains">${ts.map(t=>`<button class="rail-train ${t.between?'between':''} ${selected===t.id?'chosen':''}" data-train="${esc(t.id)}" aria-pressed="${selected===t.id}"><span>${esc(t.number)}</span><small>${esc(t.type)} · ${esc(t.direction)}</small>${t.between?'<small>駅間・付近</small>':''}</button>`).join('')}</div></div>`}).join('')+(trains.some(t=>!t.stationId)?'<p class="state-message">図上に配置できない列車は、列車一覧に表示しています。</p>':'');
  document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>{selected=b.dataset.train;render()});
  const t=trains.find(t=>t.id===selected);$('#detail').innerHTML=t?`<h2 class="big-number">${esc(t.number)}</h2><p class="detail-direction">${esc(t.name||t.type)}</p><dl><div><dt>行き先</dt><dd>${esc(t.destination)}</dd></div><div><dt>現在位置</dt><dd>${esc(t.position)}</dd></div><div><dt>遅れ</dt><dd>${t.delayMinutes===null?'情報なし':t.delayMinutes>0?esc(t.delayMinutes)+'分':'遅れ表示なし'}</dd></div><div><dt>提供元の更新時刻</dt><dd>${when(data.updatedAt)}</dd></div></dl><p class="detail-note visible-note">位置は駅・駅間単位の目安です。GPS上の正確な場所や、停車・通過の区別は表していません。</p>`:'<p class="state-message">列車が表示されたら選択できます。</p>';
  $('#provider').innerHTML=`出典：<a href="${esc(data.source)}" target="_blank" rel="noopener">${esc(data.provider)} ↗</a>`;
}
async function refresh(){if(loading||document.hidden)return;loading=true;lastCycle=Date.now();$('#refresh').disabled=true;$('#global-status').textContent='全対応路線を更新中…';const ids=lines.filter(l=>!l.unsupported).map(l=>l.id),groups=[];for(let i=0;i<ids.length;i+=4)groups.push(ids.slice(i,i+4));const control=new AbortController(),timeout=setTimeout(()=>control.abort(),25000);let next=0,failed=0;
  async function runner(){while(next<groups.length){const group=groups[next++];try{const result=await api('/api/batch?ids='+group.join(','),control.signal);if(!Array.isArray(result.items))throw Error('Bad response');for(const id of group){const item=result.items.find(i=>i.id===id);if(!item||item.error||!Array.isArray(item.trains)||!Array.isArray(item.stations)||!Number.isFinite(Date.parse(item.updatedAt))){states.set(id,{error:true});failed++}else states.set(id,item)}}catch{for(const id of group){states.set(id,{error:true});failed++}}if(group.includes(active))render()}}
  await Promise.all([runner(),runner(),runner()]);clearTimeout(timeout);loading=false;$('#refresh').disabled=false;$('#global-status').textContent=`全${ids.length}路線・区間を30秒ごとに確認${failed?' · '+failed+'件取得失敗':''}`;status();schedule();
}
function schedule(){clearTimeout(timer);timer=setTimeout(refresh,Math.max(1000,30000-(Date.now()-lastCycle)))}
async function init(){try{let data;try{data=await api('/api/lines',AbortSignal.timeout(20000))}catch{data={lines:[]}}const merged=new Map(KNOWN_ROUTES.map(l=>[l.id,l]));for(const l of data.lines||[])merged.set(l.id,l);lines=[...merged.values(),...unsupported];$('#area').innerHTML='<option value="all">全エリア</option>'+[...new Set(lines.map(l=>l.area))].map(a=>`<option>${esc(a)}</option>`).join('');fillLines();choose('hapi');await refresh()}catch{$('#global-status').textContent='接続できません。再読み込みしてください。';$('#rail-map').innerHTML='<div class="empty-state"><h2>データサービスに接続できません</h2><p>時間をおいてページを再読み込みしてください。</p></div>';$('#refresh').disabled=false}}
$('#area').onchange=()=>{fillLines();choose($('#line').value)};$('#line').onchange=e=>choose(e.target.value);$('#refresh').onclick=()=>lines.length?refresh():init();
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{if(!lines.length)return;$('#area').value='all';fillLines();choose(b.dataset.route)});
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(timer);else if(lines.length)refresh()});setInterval(status,10000);init();
